sources:
  - name: Safespace API
    handler:
      jsonSchema:
        baseUrl: ${BASE_URL}
        operationHeaders:
          Content-Type: application/json
          Authorization: Bearer {context.headers['api-token']}
        operations:
          - type: Query
            field: getTherapists
            path: therapists/list/{args.userId}
            method: GET
            responseSample: ./jsonSchemas/therapist/listSample.json
          - type: Query
            field: getSingleTherapist
            path: therapists/{args.id}
            method: GET
            responseSample: ./jsonSchemas/therapist/singleSample.json
          - type: Query
            field: userIsLoggedIn
            path: users/isLoggedIn
            method: GET
          - type: Query
            field: getUserSettings
            path: /{args.id}/settings
            method: GET
            responseSample: ./jsonSchemas/user/settingsSample.json
          
          - type: Query
            field: getUserSessions
            path: /sessions/patient/{args.id}
            method: GET
            responseSample: ./jsonSchemas/session/sessionsSample.json

          - type: Query
            field: getSession
            path: /sessions/{args.id}
            method: GET
            responseSample: ./jsonSchemas/session/getSessionSample.json
          
          - type: Query
            field: getSessionMessages
            path: /sessions/{args.id}/messages
            method: GET
            responseSample: ./jsonSchemas/session/sessionMessagesSample.json

          - type: Query
            field: saveSessionMessage
            path: /sessions/{args.id}/messages
            method: GET
            requestSample: ./jsonSchemas/session/saveSessionMessageRequestSample.json
            responseSample: ./jsonSchemas/session/saveSessionMessageResponseSample.json
         
          - type: Query
            field: getAvailabilitiesForUser
            path: /availabilities/{args.userId}
            method: GET
            responseSample: ./jsonSchemas/availability/availabilitiesResponseSample.json

          - type: Mutation
            field: createSession
            path: /sessions
            method: POST
            requestSample: ./jsonSchemas/session/sessionRequestSample.json
            responseSample: ./jsonSchemas/session/sessionResponseSample.json

          - type: Mutation
            field: deleteSession
            path: /sessions/{args.id}
            method: DELETE

          - type: Mutation
            field: updateSessionStatus
            path: /sessions/{args.id}/status
            method: PATCH
            requestSample: ./jsonSchemas/session/sessionStatusRequestSample.json
            responseSample: ./jsonSchemas/session/sessionStatusResponseSample.json

          - type: Mutation
            field: patchUserSettings
            path: /users/{args.id}/settings
            method: PATCH
            requestSample: ./jsonSchemas/user/patchSettingsRequestSample.json
            responseSample: ./jsonSchemas/user/patchSettingsResponseSample.json

          - type: Mutation
            field: loginUser
            path: /users/login
            method: POST
            requestSample: ./jsonSchemas/user/loginRequestSample.json
            responseSample: ./jsonSchemas/user/loginResponseSample.json
          - type: Mutation
            field: signupUser
            path: /users
            method: POST
            requestSample: ./jsonSchemas/user/signupRequestSample.json
            responseSample: ./jsonSchemas/user/signupResponseSample.json